
name: Run Coverity On Polaris
on: [push]

jobs:
  synopsys_coverity:
    name: Synopsys Coverity
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1      
    - name: Download Polaris CLI
      run: |
        curl http://52.188.212.142:8080/downloadFile.htm?fn=cov-analysis-linux64-2020.06.tar.gz -o cov-analysis-linux64-2020.06.tar.gz -LO -u admin:SIGpass8!
        ls -all
        tar -xf cov-analysis-linux64-2020.06.tar.gz
        ls -all
        cd cov-analysis-linux64-2020.06
        ls -all
        
    - name: npm install
      run: npm install
        
    - name: Cov-Build              
      run: |
        ./coverity/cov-analysis-linux64-2020.06/bin/cov-configure --javascript
        ./coverity/bin/cov-build --dir idir --no-command --fs-capture-search .
        
      
    #- name: npm install
    #  run: npm install        
        
    #- name: Synopsys Detect Action
    
#  uses: blackducksoftware/github-action@1.0.1
 #     env:
  #      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
   #     BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN}}
