
name: Run Coverity On Polaris
on: [push]

jobs:
  synopsys_coverity:
    name: Synopsys Coverity
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1      
    - name: Download Polaris CLI
      run: curl https://sipse.polaris.synopsys.com/api/tools/polaris_cli-linux64.zip -LO
    - name: unzip
      run: unzip polaris_cli-linux64.zip
      
    - name: Polaris Setup
      run: ./polaris setup
      
    #- name: npm install
    #  run: npm install        
        
    #- name: Synopsys Detect Action
    
#  uses: blackducksoftware/github-action@1.0.1
 #     env:
  #      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
   #     BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN}}
