name: Run Synopsys Detect
on: [push]

jobs:
  synopsys_detect_blackduck:
    name: Black Duck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1      
    - name: npm install
      run: npm install        
        
    - name: Synopsys Detect Action
      uses: blackducksoftware/github-action@1.0.1
      env:
        BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
        BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN}}

  synopsys_detect_coverity:
    name: Coverity (on Polaris)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1      
    #- run: npm install        
        
    - name: Synopsys Detect Action
      uses: blackducksoftware/github-action@1.0.1
      env:
        BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
        BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN}}
      with:
        args: --detect.polaris.enable=true --detect.tools=POLARIS --polaris.access.token=${{ secrets.POLARIS_API_TOKEN}} --polaris.url=${{ secrets.POLARIS_URL}}

